
        

<!-- <h2>Here's what our parents have to say about ELC Preschool</h2>
<br/>
<p class="testimonialText">&#8220;I&#8217;ve had two children spend three years at Emmanuel Lutheran Preschool.  All of the teachers have been excellent, the administrators are very friendly and supportive, and the specials (Creative Movement is a favorite) are great!  What particularly drew me to ELP is a warm and homey "vibe" that I felt as early as the day we came for a tour and the program director took my daughter's hand.  Both of my kids have really learned a lot, especially interacting with other kids, and I think Emmanuel Lutheran does a great job of preparing kids for kindergarten, particularly from a social standpoint.  I am so happy we chose Emmanuel Lutheran over other local preschools we looked at.&#8221;</p>
<p class="testimonialAuthor">Sarah Lundquist (parent of two children who went to Emmanuel, her last one is headed to Kindergarten this fall. 2011)</p>

<h3>Child&#8217;s note to the Director.</h3>
<p class="testimonialText">&#8220;Thank you for teaching me Chapel.  Thank you for teaching me chapel manners.  At our church, I will remember those chapel manners and the words that you say.  I think you are good and fair.&#8221;   	Love, Chloe And her parents accompanying note</p>

<p class="testimonialText">&#8220;Judging from my Chloe&#8217;s note, you made quite an impression on her-as you did to me!  Thank you for creating such a warm, child-centered, family friendly preschool environment.  Chloe felt safe and loved at ELP and because of that, she has grown so much in so many ways.  Thank you for your good works on behalf of the young lives you touch.
&#8221;</p>
<p class="testimonialAuthor">With gratitude,  Mia and Chris French family</p>
<p class="testimonialText">My son had two fantastic years at Emmanuel Lutheran Preschool (ELP). Although we are excited about starting a new chapter in our lives with elementary school, we are very sad to say goodbye to our ELP "family". Upon moving to Oakton in the summer of 2009, I immediately started scoping out preschools. After looking at a lot of them and not feeling "right" about them, a friend of mine suggested ELP. After touring the school and talking to the administrators, I knew it was the perfect school for us. Fast forward two years now and my son has had an amazing preschool experience. ELP really fosters play-based learning in a way that allows the kids learn valuable socialization skills as well as solid academics. He has had remarkable emotional growth over the past year and I am 100% sure he is ready for the (new) full day kindergarten this fall. The weekly chapel, creative movement, super science, field trips (my favorite was the walk over to Madison HS to see their fabulous Tiny Tots Christmas show!) and the optional lunch bunch were all icing on the cake. The close friendships we both made while at ELP will last a lifetime as well. Maybe it's better to say "we'll see our ELP family later", rather than goodbye! I would whole-heartedly recommend ELP to anyone looking for a preschool in the Vienna/Oakton area.</p>
<p class="testimonialAuthor">Parent Sonja Jansons</p> -->

<h2 class="col-md-10">Here's what our parents have to say about ELC Preschool</h2>
<br/>
<p class="col-md-10">&#8220;I&#8217;ve had two children spend three years at Emmanuel Lutheran Preschool.  All of the teachers have been excellent, the administrators are very friendly and supportive, and the specials (Creative Movement is a favorite) are great!  What particularly drew me to ELP is a warm and homey "vibe" that I felt as early as the day we came for a tour and the program director took my daughter's hand.  Both of my kids have really learned a lot, especially interacting with other kids, and I think Emmanuel Lutheran does a great job of preparing kids for kindergarten, particularly from a social standpoint.  I am so happy we chose Emmanuel Lutheran over other local preschools we looked at.&#8221;</p>
<p class="col-md-10" style="color:blue;">Sarah Lundquist (parent of two children who went to Emmanuel, her last one is headed to Kindergarten this fall. 2011)</p>

<h3 class="col-md-10">Child&#8217;s note to the Director.</h3>
<p class="col-md-10">&#8220;Thank you for teaching me Chapel.  Thank you for teaching me chapel manners.  At our church, I will remember those chapel manners and the words that you say.  I think you are good and fair.&#8221;   	Love, Chloe And her parents accompanying note</p>

<p class="col-md-10">&#8220;Judging from my Chloe&#8217;s note, you made quite an impression on her-as you did to me!  Thank you for creating such a warm, child-centered, family friendly preschool environment.  Chloe felt safe and loved at ELP and because of that, she has grown so much in so many ways.  Thank you for your good works on behalf of the young lives you touch.
&#8221;</p>
<p class="col-md-10" style="color:blue;">With gratitude,  Mia and Chris French family</p>
<p class="col-md-10">My son had two fantastic years at Emmanuel Lutheran Preschool (ELP). Although we are excited about starting a new chapter in our lives with elementary school, we are very sad to say goodbye to our ELP "family". Upon moving to Oakton in the summer of 2009, I immediately started scoping out preschools. After looking at a lot of them and not feeling "right" about them, a friend of mine suggested ELP. After touring the school and talking to the administrators, I knew it was the perfect school for us. Fast forward two years now and my son has had an amazing preschool experience. ELP really fosters play-based learning in a way that allows the kids learn valuable socialization skills as well as solid academics. He has had remarkable emotional growth over the past year and I am 100% sure he is ready for the (new) full day kindergarten this fall. The weekly chapel, creative movement, super science, field trips (my favorite was the walk over to Madison HS to see their fabulous Tiny Tots Christmas show!) and the optional lunch bunch were all icing on the cake. The close friendships we both made while at ELP will last a lifetime as well. Maybe it's better to say "we'll see our ELP family later", rather than goodbye! I would whole-heartedly recommend ELP to anyone looking for a preschool in the Vienna/Oakton area.</p>
<p class="col-md-10" style="color:blue;">Parent Sonja Jansons</p>